name: pytest_algorithms

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-ubuntu:
    name: "pytest_algorithms on ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install essential dependencies
        run: |
          sudo apt-get install -y libprotobuf-dev
          python -m pip install --upgrade pip setuptools
          pip install wheel
          pip install grpcio-tools==1.48.2
          pip install pytest pytest-xdist pytest-timeout pytest-retry
          pip install -r requirements-test.txt
      - name: Install Vizier
        run: |
          pip wheel -e .
          pip install -e .
          pip install -r requirements-jax.txt
          pip install -r requirements-algorithms.txt
      - name: Print installed dependencies
        run: |
          pip list
      # - name: Test with pytest is currently disabled
        # run: |
        #   pytest -q -n auto vizier/_src/algorithms/ vizier/_src/jax/ \
        #   --retries 0 --timeout=360
